teleport-on-join: false
teleport-on-void: false
scoreboard-enabled: false
allow-banned-players: false
ranked-ban-message: "&cYou are banned from playing ranked. Contact staff for more information."
mute-message: "&cYou are muted. Expires in <time>"
handle-spawn-protection: false
handle-spawn-mechanics: false
send-texturepack: false
texturepack-link: https://example.com/
sha1sum-texturepack: 4f4257210bd4019cf085338fbc90d9d3128960a5
player-msg-disabled: "&c-player has disabled private messages."
msg-send-format: "&7(&dTo -receiver&7) &b-message"
msg-receive-format: "&7(&dFrom -sender&7) &b-message"
allow-signs-crafting: false
ban-message:
  - "&4&lYou are banned"
  - "Reason: <reason>"
  - "Expires: <time>"
  - "You may purchase an unban at https://dystellar.gg/"
blacklist-message:
  - "&4&lYou are blacklisted"
  - "Reason: <reason>"
  - "Expires: Never"
  - "This type of punishment cannot be appealed."
kick-message: "&cYou have been kicked from the server. Reason: &f<reason>"
warn-message:
  - "&7&m----------------------------------"
  - " "
  - "&cYou have been warned!"
  - "Reason: <reason>"
  - " "
  - "&4Be careful, getting multiple warnings will get you banned!"
  - " "
  - "&7&m----------------------------------"
broadcast-format: "[&cBroadcast&f] &e<message>"
# Title has a limit of 16 characters, while every line has a limit of 32 characters.
####################################################################################
# Placeholders:
# <player_name>
# <ping>
####################################################################################
scoreboard:
  title: "&3Dystellar"
  lines:
    - "some text"
    - "some text"
    - "some text"
    - "some text"
  refresh-rate: 500 # in milliseconds. 1000 millis = 1 second.
freeze-message:
  - "--------------------------------"
  - "&cYou have been frozen!"
  - "--------------------------------"
unfreeze-message: "&aYou have been unfreezed. Sorry and thanks for your time!"
automated-messages-enabled: true
automated-messages-rate: 360 # in seconds.
prevent-weather-changing: true
mariadb:
  enabled: false
  host: "localhost"
  port: 3306
  database: "core"
  user: "root"
  password: "super_secret_password"
